# Generated by Django 3.2.16 on 2022-12-26 17:02

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
