# Generated by Django 3.2.16 on 2022-12-26 18:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_testimonial_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
