# Generated by Django 3.2.16 on 2022-12-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_testimonial_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
    ]
